### ISSUE TITLE
Design research and critique

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-idintegration#1]
We haven't gotten all the site requirements and design direction from the client yet, but let's get started with our own research and come up with some items the client can't say no to. 

Review the notes below and visit the links. Research the company and figure out some problems it may be having with its website. Also, think of some problems ID Integration may be wanting to solve with their website (e.g. want to look more credible for gov. agencies, land more gov. contracts, etc).

Start coming up with design sketches/mockups and possibly a WP theme you'd like to use in order to complete this site. 

Please make consistent, daily progress and provide evidence of that by posting comments/discussion here and uploading any material you create to the google drive (ctrl + f for 'integration'). 

Pull help from @rampage1213 and @jperez4509 as necessary. Lead the discussions, consult me when needed. 

http://id-integration.com/

Convert to WP

Considerable about of backlinks from years of SEO in addition to extra content that’s not necessary. 

Wait on Chris for initial Information ARchitecture

MUST maintain URL structure

Certain PDF files may need to be converted to HTML

idintegration/pdf/thefile.pdf

Would love to do social media integration for that content as well. 

Go for industrial, modern, etc. 

Include a blog as well. 

https://www.facebook.com/id.integration

due:
12-10-15   

updated due:
12-26-15  5p

**Comment by rodneystrong** [comment]
Meg, it's been at least a day. Please post any progress as requested in the issue description. Remember, daily updates; there was no mention on how large of an update each day would have (i leave that to your judgement), just that there be an update every single day.

**Comment by vanderbeam** [comment]
My initial research of this site left me with several negative first impressions. 
General thoughts on the entire sites:
- Their constant redefining of acronyms ("DoD" for example), sometimes twice on the same page. I'm torn between suggesting to always just using the full thing, or assuming anyone looking for their products would probably know what the DoD is. 
- I find their information to be more about showing off than to be quickly informative, which causes a lot of repetition. Of course very business owner wants to show off their product, but they shouldn't do so at the risk of losing their point in the process. They could be a lot less wordy and it would have the same effect and would likely hold a clients attention better. An example that comes to mind is on the bottom of the front page there is a photo and the caption reads "Congressman Rick Larsen visited ID Integration President, Gary Moe, on September 1, 2010. Rep. Larsen is on the House Armed Services Committee and is a supporter of the IUID policy." It could easily say "Congressman Rick Larsen, supported of IUID policy, meeting with Integration President Gary Moe." There's no reason for the date (and listing dates can be risky anyway. Some people will assume 5 years ago was the last time the president met with someone of significance. 
- Lastly, the language on the website seems to go back and forth between 1920's slang (phrases like "old hat") and lawyer speak (when was the last time you saw the word "aforementioned" and you WEREN'T signing a contract?). There's also some odd sentences like "Got a business etc etc." which is a very casual way of starting a sentence and isn't proper grammar. It seems like they're unsure if they want to come off as professional or a dad trying to talk using "young person" speak.

Front Page:
- There's no actual information on the front page. Aside from the section at the very bottom, every single thing on the front page is one like on text and then "Read more." There needs to be a bit more information on the from page. I actually found the section at the bottom to be much more informative than anything else. It took me way to long to figure out what the company even did, and I'm still not 100% sure!
- The third box about REID has two "Read more"s for some reason. 

Navigation:
- Having soooo many sublinks makes the ability to pad and space the links, causing them to be very small and very little hover effect. 
- For some reason "FAQs" is under the "Applications" tab. Shouldn't this be on the main nav?

Applications, Industry, Products: 
Ultimately there is way to much information here, and much of it is repeated on each other's pages. I clicked through all of these links. There is an odd sidebar navigation you can use but sometime clicking on a certain link will change to sidebar navigation to one of the other tab's navigation (clicking on "IUD Marketing"  from the Application tab for example). A user has to jump through many hoops to find what they're looking for with without breadcumbs it's hard to find your way back. This could be solved with a grid pattern display (using photos and small experts) and when you say "Read more" there is a pop up showing all the information and links related to it. I understand SEO is  important but even though you got a person to come to your site, with a product structure like this it is unlikely you will keep them there.

Consulting Service:
- This would make much more sense to have this excerpt in About Us or on the front page.

News:
- I assume the articles on here will be turned into a blog so that will solve most of the issues there. 

About Us:
- Are listing clients really necessary?
- A lot of the About Us information would be much more useful on the front page. I think the About Us should be more about founding the company, their motto, even a bit about the founder and their history.

Contact Us:
- The paragraph is pretty wordy and seems a little pointless. 

Those are my first impressions. Will update again soon.

**Comment by rodneystrong** [comment]
This is good, I like the detail of it so far. The critique is a little heavy on the specific word choice of the authors, but it's fine for now. 
Keep it up. Just a quick note, the daily feedback doesn't have to be this lengthy everyday; however feel free to maintain if you feel it's necessary.

**Comment by vanderbeam** [comment]
This is the theme I had in mind to use: https://wordpress.org/themes/asteria-lite/

**Comment by vanderbeam** [comment]
I feel it's minimalist enough to not be distracting with a lot of flashy details, but is sleek and interesting.

**Comment by vanderbeam** [comment]
I would of course change the colours. Honestly, I like the red they have on their current site.

**Comment by vanderbeam** [comment]
I AM SO MAD AT MYSELF! Quintin, Joel and I had a very productive meeting today that I was recording and had intended on sending to you, but when I went to play it back I realized I didn't have my mic driver installed on my laptop! I've attached the photos we took of our white board notes. (next time we'll take notes during the meeting too....)

Q and J but had very helpful input and together we were able to make up the front page mock-up based off of the theme (listed above) that I want to use. 

I have a lot to say about this project and it would take age to type and read, so I'm going to make a video and upload it soon. I will present it as if I were presenting it the client in case you find it a useful tool to pass onto him. 

![slack_for_ios_upload_1024 2](https://cloud.githubusercontent.com/assets/12962001/11886571/5f527008-a4e0-11e5-8f90-95c8353e66c1.jpg)
![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/12962001/11886573/5f5492b6-a4e0-11e5-92c4-e088fcaa749f.jpg)
![slack_for_ios_upload_1024 1](https://cloud.githubusercontent.com/assets/12962001/11886572/5f528dfe-a4e0-11e5-9e86-aca4cb8ca771.jpg)

**Comment by rodneystrong** [comment]
This is good, I really like the effort you're putting into this. 

I want to warn you; there's a chance they'll want to take a completely different direction, but I still want us to be prepared with expert opinions. 

The ownership you're putting into this is exactly what I'm expecting of you. Please keep this up. 

Remember, daily updates. They don't all need to be monumental. Even if there wasn't any progress made for a day on this project, I'm totally cool with you saying, "I didn't get to this project today, but tomorrow's looking good".

**Comment by vanderbeam** [comment]
Here's a vid that kinda sums up the meeting. @jperez4509 and @rampage1213, I'd love for you check it out and mention anything I may have missed/forgotten. 
http://screencast-o-matic.com/watch/colFY4hy3h

**Comment by irms** [comment]
I love how this communication is happening. Good work @vanderbeam.

**Comment by rodneystrong** [comment]
I see you used screencast - o - matic.. nice  ;D  
jason's getting married tomorrow, so i'll check out the video on sunday and comment here.

**Comment by rodneystrong** [comment]
Just watched the video. Glad you did it. I agree with you on most points. I'll start a discussion with you on the others. 

Please transcribe your video into typed notes (google doc in our drive). Break up your document in this format: 

- Overall site notes (includes all the comments you have about the logo discussion, information architecture, social media, etc. )

- Home page

- Applications page

- Industry page

- Pretty much every page should have it's own section 

Make this part of your daily progress. There are 3 days left of work until the 24th, so plan accordingly. You'll also have the 26th. 

due:
12-26-15   5p

**Comment by rodneystrong** [comment]
Also, feel free to add sections that aren't just about the pages that also don't belong in the previous sections I outlined.

**Comment by vanderbeam** [comment]
HOME PAGE:
Header –
-	Logo: The QR code in the logo should actually go somewhere (their homepage, for example). This would make marketing tools such as banners, business cards, etcetera a quick way for someone to access the website on the spot without typing it in
o	I realize the code in the logo is actually an IUID scan code, which is a nice touch but considering it’s so similar to a QR code, this may still be up for consideration 
-	Slogan: Going Beyond the Mark: When combined with the banner’s current slideshow of fighter jets and tanks blowing things up, having the slogan at the top there really gives the impression that maybe you’re selling actual missiles or other weapons. 
-	
-	
Slider –
-	While yes, they get across that the company’s target demographic is the military, it would be much less ambiguous if they were of photos of the actual product (scanners, labels, etc)
-	The taglines on the slider images should be a little more about the company or a specific product. “Providing integration solutions from MIL-STD-130 to NASA, ATA Spec2000, and everything in between” and “Identification and asset tracking solutions for your most challenging applications” are good, but the rest seem more like information you should get from the rest of the site. The tag line on the ID-Int. Twitter (“MIL-STD-130 DOD & ATA SPEC compliance is our business—Permanent, durable #IUID labels w/ BarCodeOS to keep track of warehouse assets, & RFID location tracking.”) should also be one of the slider image captions. One of the sliders should also list a couple of the clients, but in a classy way; for example: “We’ve been proudly serving organizations such as United Airlines, the US Navy, and Rockwell since (year founded).” And then a Read More link that leads to About Us.
Four Column Section –
-	Jumps right into trying to sell you the product when the company’s information is still a little vague. This section above the fold would be more appealing if it were about the company. This is the opportunity to give anyone visiting the site more detail about what the site offers so visitors KNOW they’re in the right place
-	This would be moved a little further down the page but instead of having captions like “Intelligent Scanners” and “IUID Systems Integration” which currently give the site more of an information feel and less that you’re actually selling these products, they would go to the Products, Application, and Industry pages where visitors would learn more there (this would go below the CTA)
CTA – 
-	Below that is a great place for a CTA where after reading a bit about the company a visit seeing “ID INTEGRATION: GOING BEYOND THE MARK” would make much more sense
Consulting Services –
-	This button needs to be taken out of the navigation bar. It essentially just talks about great customer service and being there with you when you need it and would look much more appealing if it were right on the front page. This way visitors don’t have to go to a completely different page just to be affirmed that the company stands by its clients. 
Blog – 
-	Far too many “Read More” links appear on the website. Simply by using WordPress, a lot of the blog issues will be corrected (the titles of the blog posts will be the links along with an excerpt). Having full page blog/news post is ultimately an unnecessary waste of space.  It will look much more attractive with the narrow column of “Recent posts” type widget you get when using WordPress.
Bottom section on current site –
-	All the information will be placed in different areas
FOOTER
-	Contact information (currently in the aforementioned bottom section)
-	Blog Post
-	If using a larger footer, it may be appropriate to use a site map since there are so many links on this particular site
-	Contact Form; having a contact form in the footer that will show up on every page reaffirms that the company is always willing to hear from you
NAVIGATION
-	IUID FAQs (currently under Applications) needs to be its own nav bar link
APPLICATIONS, INDUSTRY, PRODUCTS
-	Ultimately each one of these pages has a ton of information and is very overwhelming. It would be much more attractive to put the products listed with a bold caption into a grid format instead and perhaps scrap the side navigation all together because it tends to be confusing. 
o	For example, clicking on the Applications navigation tab will take you to the main Application page, but if you click on the first item from the Application drop down menu (“RFID Location Tracking”) it actually take you to the Product’s page. However if I then click on the “Custom/Turnkey Solutions,” while still in the Products side nav, you will see that the side nav is different once again as there are so many links, clearly not all of them have been updated to the current side nav (If the side nav were to continue to be implemented, this issue would be solved again by simply using WordPress). However, clicking on “Marketing Hardware” I’m once again taken to a different side nav. This is very confusing to visitors who want to get back to a product but aren’t sure how they got there at this point. 
ABOUT US
-	This page contains a bit of repetitive information about how great the products are. Generally, About Us pages are about the company itself, not so much the products. An opening paragraph about when the company was founded and a bit about the founders and who’s the president now is appropriate. After that is when you get to brag a little bit more about the company’s success and then continue to list the clients that are currently on the About Us page. This is also a good place for the photo of Congressman Rick Larsen and Gary Moe (however, I would leave out the date. Listing dates on things like photos and awards can make some visitors think, “what, you haven’t had anything else to brag about since 2010?” when a simple caption such as “Congressman Rick Larsen, House Armed Services Committee and supporter of the IUID policy, visiting with ID Integration President, Gary Moe.” Would be concise and impressive enough).
GENERAL NOTES
-	There needs to be more calls to action on the site 
-	Less Read More. As it stands, it seems you need to click through several links to get to the product or information a visitor may be interesting in (WordPress offers a plugin called “Redirect” that will allow us to redirect any links to the new page without having to worry about any SEO or URL loss)
-	Less photos of places and tanks and such and more photos of the products themselves 
-	A lot of the photos used in the products contain valuable information in the photo itself… this is bad for SEO and should actually be just the photo itself with that information stated on the page.

**Comment by vanderbeam** [comment]
@rodneystrong I felt I did a fine enough job describing things wherein screen shots weren't required and felt my time was better spent bring the vision to life a bit (The "Applications" image is the format Industry and Products would have, also). I realize I didn't add the social icons because there are several spot we had in mind
@jperez4509  @rampage1213 -- is this accurate?

![wireframe_applications](https://cloud.githubusercontent.com/assets/12962001/12029945/31e2de40-adab-11e5-8d4e-7a77066fdb8a.jpg)
![wireframe_home](https://cloud.githubusercontent.com/assets/12962001/12029946/31e44b36-adab-11e5-9186-b6243a90eaf1.jpg)

**Comment by rodneystrong** [comment]
This is excellent. Thank you for doing this and posting mockups of the potential design. This puts us in a good position to present well-thought ideas to the client.

@rampage1213 @jperez4509   can you comment here please? what do you remember from the meeting that isn't documented here?

**Comment by rampage1213** [comment]
This is everything from the meeting. One thing looking at megs design I like it but I think if she made the application page look more like Estate Research Testimonial page layout it might look better.

**Comment by rodneystrong** [comment]
Thanks @rampage1213 

Don't forget @jperez4509 , need your input here too.

**Comment by jperez4509** [comment]
@vanderbeam is very thorough and wrote down everything we talked about. I agree with @rampage1213 about not loving the Applications page design, but I do like the way everything in the Home page is laid out. One thing I might edit is having the contact form on the footer of every page.

**Comment by rodneystrong** [comment]
Perfect, thanks for the input everyone. The content from this issue will be hepful as we build out the site.
